DROP TABLE IF EXISTS user_actions;
CREATE TABLE IF NOT EXISTS user_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    event_id BIGINT,
    action_type VARCHAR,
    action_weight DOUBLE PRECISION,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (user_id, event_id)
);

DROP TABLE IF EXISTS similarities;
CREATE TABLE IF NOT EXISTS similarities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_a BIGINT,
    event_b BIGINT,
    score DOUBLE PRECISION,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (event_a, event_b)
);