DROP TABLE IF EXISTS compilation_events;
--  DROP TABLE IF EXISTS participation_requests;
--  DROP TABLE IF EXISTS events;
--  DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS categories;


CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,

    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_categories_name UNIQUE (name),
    CONSTRAINT ck_categories_name CHECK (LENGTH(name) >= 1)
);

-- CREATE TABLE IF NOT EXISTS locations (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     name VARCHAR(120),
--     address VARCHAR(255),
--     latitude DOUBLE PRECISION NOT NULL,
--     longitude DOUBLE PRECISION NOT NULL,
--     creator_id BIGINT,
--     state VARCHAR(14) NOT NULL DEFAULT 'PENDING',
--
--     CONSTRAINT pk_locations PRIMARY KEY (id),
--     CONSTRAINT chk_lat CHECK (latitude >= -90 AND latitude <= 90),
--     CONSTRAINT chk_lon CHECK (longitude >= -180 AND longitude <= 180),
--     CONSTRAINT chk_location_state CHECK (state IN ('PENDING', 'APPROVED', 'REJECTED', 'AUTO_GENERATED')),
--     CONSTRAINT uq_coords_name UNIQUE (name, latitude, longitude)
-- );


-- CREATE TABLE IF NOT EXISTS events (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     title VARCHAR(120) NOT NULL,
--     annotation VARCHAR(2000) NOT NULL,
--     description TEXT,
--     category_id BIGINT NOT NULL,
--     initiator_id BIGINT NOT NULL,
--     location_id BIGINT NOT NULL,
--     event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--     created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     published_on TIMESTAMP WITHOUT TIME ZONE,
--     paid BOOLEAN NOT NULL DEFAULT FALSE,
--     participant_limit INT DEFAULT 0,
--     request_moderation BOOLEAN DEFAULT TRUE,
--     state VARCHAR(20) NOT NULL,
--
--     CONSTRAINT pk_events PRIMARY KEY (id),
--     CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories (id),
-- --     CONSTRAINT fk_location FOREIGN KEY (location_id) REFERENCES locations (id),
--     CONSTRAINT chk_state CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED'))
-- );


-- Таблица подборок (compilations)
CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(255)          NOT NULL,
    pinned BOOLEAN DEFAULT FALSE NOT NULL
);

-- Связующая таблица для связи "подборка-события" (many-to-many)
CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,

    CONSTRAINT pk_compilation_events
        PRIMARY KEY (compilation_id, event_id),

    CONSTRAINT fk_compilation
        FOREIGN KEY (compilation_id)
            REFERENCES compilations (id)
            ON DELETE CASCADE
);

-- CREATE TABLE IF NOT EXISTS participation_requests
-- (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     requester_id BIGINT NOT NULL,
--     event_id BIGINT NOT NULL,
--     created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     status VARCHAR(20) NOT NULL,
--
--     CONSTRAINT fk_event1 FOREIGN KEY (event_id) REFERENCES events (id),
--     CONSTRAINT chk_status CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED'))
-- );

-- CREATE OR REPLACE FUNCTION calculate_distance_meters(
--     lat1 double precision,
--     lon1 double precision,
--     lat2 double precision,
--     lon2 double precision
-- ) RETURNS double precision AS $$
--     SELECT 6371000 * 2 * ATAN2(
--         SQRT(
--             SIN(RADIANS(lat2 - lat1)/2)^2 +
--             COS(RADIANS(lat1)) * COS(RADIANS(lat2)) * SIN(RADIANS(lon2 - lon1)/2)^2
--         ),
--         SQRT(1 - (
--             SIN(RADIANS(lat2 - lat1)/2)^2 +
--             COS(RADIANS(lat1)) * COS(RADIANS(lat2)) * SIN(RADIANS(lon2 - lon1)/2)^2
--         ))
--     )
-- $$ LANGUAGE SQL;
