package ru.practicum.ewm.service;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;
import ru.practicum.ewm.client.CategoryClient;
import ru.practicum.ewm.client.LocationClient;
import ru.practicum.ewm.client.RequestClient;
import ru.practicum.ewm.client.UserClient;
import ru.practicum.ewm.dto.CategoryDtoOut;
import ru.practicum.ewm.dto.EventCreateDto;
import ru.practicum.ewm.dto.EventDtoOut;
import ru.practicum.ewm.dto.EventShortDtoOut;
import ru.practicum.ewm.dto.EventUpdateAdminDto;
import ru.practicum.ewm.dto.EventUpdateDto;
import ru.practicum.ewm.dto.LocationAutoRequest;
import ru.practicum.ewm.dto.LocationDto;
import ru.practicum.ewm.dto.LocationFullDtoOut;
import ru.practicum.ewm.dto.LocationState;
import ru.practicum.ewm.dto.RequestsCountDto;
import ru.practicum.ewm.dto.UserDtoOut;
import ru.practicum.ewm.exception.ConditionNotMetException;
import ru.practicum.ewm.exception.NoAccessException;
import ru.practicum.ewm.exception.NotFoundException;
import ru.practicum.ewm.mapper.EventMapper;
import ru.practicum.ewm.model.Event;
import ru.practicum.ewm.model.EventAdminFilter;
import ru.practicum.ewm.model.EventFilter;
import ru.practicum.ewm.model.EventState;
import ru.practicum.ewm.repository.EventRepository;
import ru.practicum.statsclient.StatsClient;
import ru.practicum.statsclient.StatsClientException;
import ru.practicum.statsdto.StatsDtoOut;

import static ru.practicum.ewm.constants.Constants.STATS_EVENTS_URL;

@Slf4j
@Service
@RequiredArgsConstructor
public class EventServiceImpl implements EventService {

    private static final int MIN_TIME_TO_UNPUBLISHED_EVENT = 2;
    private static final int MIN_TIME_TO_PUBLISHED_EVENT = 1;

    private final EventRepository eventRepository;
    private final UserClient userClient;
    private final CategoryClient categoryClient;
    private final RequestClient requestClient;
    private final StatsClient statsClient;
    private final LocationClient locationClient;
    private final TransactionTemplate transactionTemplate;
    private final EventMapper eventMapper;

    @Override
    public EventDtoOut add(Long userId, EventCreateDto eventDto) {

        validateEventDate(eventDto.getEventDate(), EventState.PENDING);

        // Внешние вызовы — вне транзакции
        CategoryDtoOut category = getCategoryOrThrow(eventDto.getCategoryId());
        UserDtoOut initiator = getUserOrThrow(userId);
        Long locationId = resolveLocationId(eventDto.getLocation());

        Event event = transactionTemplate.execute(status -> {
            Event e = eventMapper.fromCreateDto(eventDto);
            e.setInitiatorId(userId);
            e.setCategoryId(category.getId());
            e.setLocationId(locationId);
            return eventRepository.save(e);
        });

        assert event != null;
        LocationDto location = loadLocation(event.getLocationId());
        if (location == null && eventDto.getLocation() != null) {
            LocationDto fallback = new LocationDto();
            fallback.setId(event.getLocationId());
            fallback.setLatitude(eventDto.getLocation().getLatitude());
            fallback.setLongitude(eventDto.getLocation().getLongitude());
            location = fallback;
        }

        return eventMapper.toDto(event, category, initiator, location);
    }

    private Long resolveLocationId(LocationDto dto) {
        // 1. Если прислали id — просто используем его, но валидируем
        if (dto.getId() != null) {
            LocationFullDtoOut full = locationClient.getLocationById(dto.getId());
            if (full == null) {
                throw new NotFoundException("Location", dto.getId());
            }
            if (!isLocationUsableForEvent(full)) {
                throw new ConditionNotMetException("Location cannot be used for events");
            }
            return full.getId();
        }

        // 2. id нет — автогенерация по координатам
        LocationAutoRequest req = LocationAutoRequest.builder()
                .latitude(dto.getLatitude())
                .longitude(dto.getLongitude())
                .build();

        LocationFullDtoOut auto = locationClient.getOrCreateAutoGenerated(req);
        if (auto == null) {
            throw new ConditionNotMetException("Cannot resolve location for given coordinates");
        }
        return auto.getId();
    }

    private boolean isLocationUsableForEvent(LocationFullDtoOut full) {
        // enum LocationState {PENDING, APPROVED, REJECTED, AUTO_GENERATED}
        return full.getState() == LocationState.APPROVED
                || full.getState() == LocationState.AUTO_GENERATED;
    }

    @Override
    public EventDtoOut update(Long userId, Long eventId, EventUpdateDto eventDto) {

        log.warn(
                "[UPDATE_EVENT_TRACE] userId={}, eventId={}, incomingDto={}",
                userId, eventId, eventDto
        );

        // Если нужно сменить категорию — валидируем её до транзакции
        CategoryDtoOut newCategory;
        if (eventDto.getCategoryId() != null) {
            newCategory = getCategoryOrThrow(eventDto.getCategoryId());
        } else {
            newCategory = null;
        }

        Event updated = transactionTemplate.execute(status -> {
            Event event = getEvent(eventId);

            log.warn(
                    "[UPDATE_EVENT_TRACE] loadedEventBeforeUpdate id={}, participantLimit={}, state={}",
                    event.getId(), event.getParticipantLimit(), event.getState()
            );

            if (!event.getInitiatorId().equals(userId)) {
                log.warn("[UPDATE_EVENT_TRACE] NO ACCESS: initiator={}, userId={}",
                        event.getInitiatorId(), userId);
                throw new NoAccessException("Only initiator can edit the event");
            }

            if (event.getState() == EventState.PUBLISHED) {
                log.warn("[UPDATE_EVENT_TRACE] UPDATE_BLOCKED: event is published");
                throw new ConditionNotMetException("Cannot update published event");
            }

            if (eventDto.getParticipantLimit() != null) {
                log.warn(
                        "[UPDATE_EVENT_TRACE] updating participantLimit old={}, new={}",
                        event.getParticipantLimit(),
                        eventDto.getParticipantLimit()
                );
            }

            Optional.ofNullable(eventDto.getTitle()).ifPresent(event::setTitle);
            Optional.ofNullable(eventDto.getAnnotation()).ifPresent(event::setAnnotation);
            Optional.ofNullable(eventDto.getDescription()).ifPresent(event::setDescription);
            Optional.ofNullable(eventDto.getPaid()).ifPresent(event::setPaid);
            Optional.ofNullable(eventDto.getLocationId()).ifPresent(event::setLocationId);
            Optional.ofNullable(eventDto.getParticipantLimit()).ifPresent(event::setParticipantLimit);
            Optional.ofNullable(eventDto.getRequestModeration()).ifPresent(event::setRequestModeration);

            if (newCategory != null) {
                log.warn("[UPDATE_EVENT_TRACE] updating category old={}, new={}",
                        event.getCategoryId(), newCategory.getId());
                event.setCategoryId(newCategory.getId());
            }

            if (eventDto.getEventDate() != null) {
                log.warn("[UPDATE_EVENT_TRACE] updating eventDate new={}", eventDto.getEventDate());
                validateEventDate(eventDto.getEventDate(), event.getState());
                event.setEventDate(eventDto.getEventDate());
            }

            log.warn(
                    "[UPDATE_EVENT_TRACE] BEFORE_SAVE eventId={}, participantLimit={}",
                    event.getId(), event.getParticipantLimit()
            );

            log.warn("[UPDATE_EVENT_TRACE] stateAction received = {}", eventDto.getStateAction());
            if (eventDto.getStateAction() != null) {
                switch (eventDto.getStateAction()) {
                    case SEND_TO_REVIEW -> event.setState(EventState.PENDING);
                    case CANCEL_REVIEW -> event.setState(EventState.CANCELED);
                }
            }

            Event saved = eventRepository.save(event);

            log.warn(
                    "[UPDATE_EVENT_TRACE] AFTER_SAVE eventId={}, participantLimit={}",
                    saved.getId(), saved.getParticipantLimit()
            );

            return saved;
        });

        assert updated != null;
        UserDtoOut initiator = getUserOrThrow(updated.getInitiatorId());
        LocationDto location = loadLocation(updated.getLocationId());
        CategoryDtoOut category = newCategory != null
                ? newCategory
                : getCategoryOrThrow(updated.getCategoryId());

        return eventMapper.toDto(updated, category, initiator, location);
    }

    @Override
    public EventDtoOut update(Long eventId, EventUpdateAdminDto eventDto) {

        // Валидация новой категории — до транзакции
        CategoryDtoOut newCategory;
        if (eventDto.getCategoryId() != null) {
            newCategory = getCategoryOrThrow(eventDto.getCategoryId());
        } else {
            newCategory = null;
        }

        Event updated = transactionTemplate.execute(status -> {

            Event event = getEvent(eventId);

            Optional.ofNullable(eventDto.getTitle()).ifPresent(event::setTitle);
            Optional.ofNullable(eventDto.getAnnotation()).ifPresent(event::setAnnotation);
            Optional.ofNullable(eventDto.getDescription()).ifPresent(event::setDescription);
            Optional.ofNullable(eventDto.getParticipantLimit()).ifPresent(event::setParticipantLimit);
            Optional.ofNullable(eventDto.getPaid()).ifPresent(event::setPaid);
            Optional.ofNullable(eventDto.getLocationId()).ifPresent(event::setLocationId);
            Optional.ofNullable(eventDto.getParticipantLimit()).ifPresent(event::setParticipantLimit);
            Optional.ofNullable(eventDto.getRequestModeration()).ifPresent(event::setRequestModeration);

            if (newCategory != null) {
                event.setCategoryId(newCategory.getId());
            }

            if (eventDto.getEventDate() != null) {
                validateEventDate(eventDto.getEventDate(), event.getState());
                event.setEventDate(eventDto.getEventDate());
            }

            if (eventDto.getStateAction() != null) {
                switch (eventDto.getStateAction()) {
                    case PUBLISH_EVENT -> publishEvent(event);
                    case REJECT_EVENT -> rejectEvent(event);
                }
            }

            return eventRepository.save(event);
        });

        assert updated != null;
        UserDtoOut initiator = getUserOrThrow(updated.getInitiatorId());
        LocationDto location = loadLocation(updated.getLocationId());
        CategoryDtoOut category = newCategory != null
                ? newCategory
                : getCategoryOrThrow(updated.getCategoryId());

        return eventMapper.toDto(updated, category, initiator, location);
    }

    @Override
    public EventDtoOut findPublished(Long eventId) {

        Event event = eventRepository.findPublishedById(eventId)
                .orElseThrow(() -> new NotFoundException("Event", eventId));

        enrichWithConfirmedRequestsCount(List.of(event));
        enrichWithViewsCount(List.of(event));

        UserDtoOut initiator = getUserOrThrow(event.getInitiatorId());
        LocationDto location = loadLocation(event.getLocationId());
        CategoryDtoOut category = getCategoryOrThrow(event.getCategoryId());

        return eventMapper.toDto(event, category, initiator, location);
    }

    @Override
    public EventDtoOut find(Long userId, Long eventId) {

        getUserOrThrow(userId);

        Event event = getEvent(eventId);

        if (!event.getInitiatorId().equals(userId)) {
            throw new NoAccessException("Only initiator can view this event");
        }

        enrichWithConfirmedRequestsCount(List.of(event));
        enrichWithViewsCount(List.of(event));

        UserDtoOut initiator = getUserOrThrow(event.getInitiatorId());
        LocationDto location = loadLocation(event.getLocationId());

        return eventMapper.toDto(event, initiator, location);
    }

    @Override
    public Collection<EventShortDtoOut> findShortEventsBy(EventFilter filter) {
        Specification<Event> spec = buildSpecification(filter);
        Collection<Event> events = findBy(spec, filter.getPageable());

        Map<Long, UserDtoOut> usersById = loadUsersForEvents(events);
        Map<Long, CategoryDtoOut> categoriesById = loadCategoriesForEvents(events);

        return events.stream()
                .map(event -> {
                    UserDtoOut initiator = usersById.get(event.getInitiatorId());
                    CategoryDtoOut category = categoriesById.get(event.getCategoryId());
                    return eventMapper.toShortDto(event, category, initiator);
                })
                .toList();
    }

    @Override
    public Collection<EventDtoOut> findFullEventsBy(EventAdminFilter filter) {
        Specification<Event> spec = buildSpecification(filter);
        Collection<Event> events = findBy(spec, filter.getPageable());

        Map<Long, UserDtoOut> usersById = loadUsersForEvents(events);
        Map<Long, CategoryDtoOut> categoriesById = loadCategoriesForEvents(events);

        return events.stream()
                .map(event -> {
                    UserDtoOut initiator = usersById.get(event.getInitiatorId());
                    LocationDto location = loadLocation(event.getLocationId());
                    CategoryDtoOut category = categoriesById.get(event.getCategoryId());
                    return eventMapper.toDto(event, category, initiator, location);
                })
                .toList();
    }

    private Map<Long, CategoryDtoOut> loadCategoriesForEvents(Collection<Event> events) {
        return events.stream()
                .map(Event::getCategoryId)
                .filter(Objects::nonNull)
                .distinct()
                .collect(Collectors.toMap(
                        id -> id,
                        this::getCategoryOrThrow
                ));
    }

    private Collection<Event> findBy(Specification<Event> spec, Pageable pageable) {
        Collection<Event> events = eventRepository.findAll(spec, pageable).getContent();
        enrichWithConfirmedRequestsCount(events);
        enrichWithViewsCount(events);
        return events;
    }

    private Specification<Event> buildSpecification(EventAdminFilter filter) {
        return Stream.of(
                        optionalSpec(EventSpecifications.withUsers(filter.getUsers())),
                        optionalSpec(EventSpecifications.withCategoriesIn(filter.getCategories())),
                        optionalSpec(EventSpecifications.withStatesIn(filter.getStates())),
                        optionalSpec(EventSpecifications.withRangeStart(filter.getRangeStart())),
                        optionalSpec(EventSpecifications.withRangeEnd(filter.getRangeEnd())),
                        optionalSpec(EventSpecifications.withLocationId(filter.getLocationId())),
                        optionalSpec(EventSpecifications.withCoordinates(filter.getZone()))
                )
                .filter(Objects::nonNull)
                .reduce(Specification::and)
                .orElse((root, query, cb) -> cb.conjunction());
    }

    private Specification<Event> buildSpecification(EventFilter filter) {
        return Stream.of(
                        optionalSpec(EventSpecifications.withTextContains(filter.getText())),
                        optionalSpec(EventSpecifications.withCategoriesIn(filter.getCategories())),
                        optionalSpec(EventSpecifications.withPaid(filter.getPaid())),
                        optionalSpec(EventSpecifications.withState(filter.getState())),
                        optionalSpec(EventSpecifications.withLocationId(filter.getLocationId())),
                        optionalSpec(EventSpecifications.withCoordinates(filter.getZone())),
                        optionalSpec(EventSpecifications.withOnlyAvailable(filter.getOnlyAvailable())),
                        optionalSpec(EventSpecifications.withRangeStart(filter.getRangeStart())),
                        optionalSpec(EventSpecifications.withRangeEnd(filter.getRangeEnd()))
                )
                .filter(Objects::nonNull)
                .reduce(Specification::and)
                .orElse((root, query, cb) -> cb.conjunction());
    }

    private static <T> Specification<T> optionalSpec(Specification<T> spec) {
        return spec;
    }

    @Override
    public Collection<EventShortDtoOut> findByInitiator(Long userId, Integer offset, Integer limit) {

        getUserOrThrow(userId);

        Collection<Event> events = eventRepository.findByInitiatorId(userId, offset, limit);
        enrichWithConfirmedRequestsCount(events);
        enrichWithViewsCount(events);

        Map<Long, UserDtoOut> usersById = loadUsersForEvents(events);

        return events.stream()
                .map(event -> eventMapper.toShortDto(
                        event,
                        usersById.get(event.getInitiatorId())
                ))
                .toList();
    }

    private void enrichWithConfirmedRequestsCount(Collection<Event> events) {
        if (events.isEmpty()) {
            return;
        }

        List<Long> ids = events.stream()
                .map(Event::getId)
                .toList();

        List<RequestsCountDto> requestsCounts =
                requestClient.countConfirmedRequestsForEvents(ids);

        if (requestsCounts.isEmpty()) {
            return;
        }

        Map<Long, Integer> counts = requestsCounts.stream()
                .collect(Collectors.toMap(
                        RequestsCountDto::getEventId,
                        RequestsCountDto::getCount
                ));

        events.forEach(e ->
                e.setConfirmedRequests(counts.getOrDefault(e.getId(), 0))
        );
    }

    private void enrichWithViewsCount(Collection<Event> events) {
        if (events.isEmpty()) {
            return;
        }

        Map<Long, Integer> hitsMap = getStatistics(events.stream()
                .map(Event::getId)
                .toList());

        if (hitsMap.isEmpty()) {
            return;
        }

        events.forEach(dto ->
                dto.setViews(hitsMap.getOrDefault(dto.getId(), 0))
        );
    }

    private Map<Long, Integer> getStatistics(Collection<Long> ids) {
        Collection<StatsDtoOut> stats = List.of();
        if (ids.isEmpty()) {
            return Map.of();
        }

        try {
            stats = statsClient.getStats(
                    LocalDateTime.now().minusYears(10),
                    LocalDateTime.now().plusYears(10),
                    ids.stream().map(id -> STATS_EVENTS_URL + id).toList(),
                    true);
        } catch (StatsClientException ex) {
            log.error(ex.getMessage());
        }

        if (stats.isEmpty()) {
            return Map.of();
        }

        Map<String, Integer> hits = stats.stream()
                .collect(Collectors.toMap(
                        StatsDtoOut::getUri,
                        StatsDtoOut::getHits
                ));

        return ids.stream()
                .collect(Collectors.toMap(
                        num -> num,
                        num -> hits.getOrDefault(STATS_EVENTS_URL + num, 0)
                ));
    }

    private void validateEventDate(LocalDateTime eventDate, EventState state) {
        if (eventDate == null) {
            throw new IllegalArgumentException("eventDate is null");
        }

        int hours = state == EventState.PUBLISHED
                ? MIN_TIME_TO_PUBLISHED_EVENT
                : MIN_TIME_TO_UNPUBLISHED_EVENT;

        if (eventDate.isBefore(LocalDateTime.now().plusHours(hours))) {
            String message = "The event date must be no earlier than %d hours from the %s time"
                    .formatted(hours, state == EventState.PUBLISHED ? "publishing" : "current");
            throw new ConditionNotMetException(message);
        }
    }

    private CategoryDtoOut getCategoryOrThrow(Long id) {
        try {
            CategoryDtoOut dto = categoryClient.getCategoryById(id);
            if (dto == null) {
                throw new NotFoundException("Category", id);
            }
            return dto;
        } catch (Exception e) {
            throw new NotFoundException("Category", id);
        }
    }

    private Event getEvent(Long eventId) {
        return eventRepository.findById(eventId)
                .orElseThrow(() -> new NotFoundException("Event", eventId));
    }

    private void publishEvent(Event event) {
        if (event.getState() != EventState.PENDING) {
            throw new ConditionNotMetException("Events must be in 'pending' status to be published");
        }

        validateEventDate(event.getEventDate(), EventState.PUBLISHED);

        event.setState(EventState.PUBLISHED);
        event.setPublishedOn(LocalDateTime.now());
    }

    private void rejectEvent(Event event) {
        if (event.getState() == EventState.PUBLISHED) {
            throw new ConditionNotMetException("Published events cannot be rejected");
        }
        event.setState(EventState.CANCELED);
    }

    // === helpers для пользователей ===

    private UserDtoOut getUserOrThrow(Long userId) {
        try {
            UserDtoOut user = userClient.getUserById(userId);
            if (user == null) {
                throw new NotFoundException("User", userId);
            }
            return user;
        } catch (NotFoundException e) {
            throw e;
        } catch (Exception e) {
            throw new NotFoundException("User", userId);
        }
    }

    private Map<Long, UserDtoOut> loadUsersForEvents(Collection<Event> events) {
        if (events.isEmpty()) {
            return Map.of();
        }

        List<Long> ids = events.stream()
                .map(Event::getInitiatorId)
                .filter(Objects::nonNull)
                .distinct()
                .toList();

        if (ids.isEmpty()) {
            return Map.of();
        }

        List<UserDtoOut> users;
        try {
            users = userClient.getUsers(ids);
        } catch (Exception e) {
            log.error("Error fetching users for events: {}", e.getMessage(), e);
            return Map.of();
        }

        return users.stream()
                .collect(Collectors.toMap(UserDtoOut::getId, u -> u));
    }

    private LocationDto loadLocation(Long locationId) {
        if (locationId == null) {
            return null;
        }
        try {
            LocationFullDtoOut full = locationClient.getLocationById(locationId);
            if (full == null) {
                return null;
            }
            return eventMapper.toShortLocationDto(full);
        } catch (Exception e) {
            log.error("Error fetching location {}: {}", locationId, e.getMessage());
            return null;
        }
    }
}