DROP TABLE IF EXISTS participation_requests;

CREATE TABLE IF NOT EXISTS participation_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT                      NOT NULL,
    event_id     BIGINT                      NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status       VARCHAR(20)                 NOT NULL,

--     CONSTRAINT fk_event1 FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT chk_status CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED'))
);