DROP TABLE IF EXISTS events CASCADE;
--  constraint fk_event on table compilation_events depends on table events
CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(120)                            NOT NULL,
    annotation         VARCHAR(2000)                           NOT NULL,
    description        TEXT,
    category_id        BIGINT                                  NOT NULL,
    initiator_id       BIGINT                                  NOT NULL,
    location_id        BIGINT                                  NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE                      DEFAULT CURRENT_TIMESTAMP,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    paid               BOOLEAN                                 NOT NULL DEFAULT FALSE,
    participant_limit  INT                                              DEFAULT 0,
    request_moderation BOOLEAN                                          DEFAULT TRUE,
    state              VARCHAR(20)                             NOT NULL,

    CONSTRAINT pk_events PRIMARY KEY (id),
--     CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories (id),
--     CONSTRAINT fk_location FOREIGN KEY (location_id) REFERENCES locations (id),
    CONSTRAINT chk_state CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED'))
);
