DROP TABLE IF EXISTS locations CASCADE;

CREATE TABLE IF NOT EXISTS locations
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(120),
    address    VARCHAR(255),
    latitude   DOUBLE PRECISION                        NOT NULL,
    longitude  DOUBLE PRECISION                        NOT NULL,
    creator_id BIGINT,
    state      VARCHAR(14)                             NOT NULL DEFAULT 'PENDING',

    CONSTRAINT pk_locations PRIMARY KEY (id),
    CONSTRAINT chk_lat CHECK (latitude >= -90 AND latitude <= 90),
    CONSTRAINT chk_lon CHECK (longitude >= -180 AND longitude <= 180),
    CONSTRAINT chk_location_state CHECK (state IN ('PENDING', 'APPROVED', 'REJECTED', 'AUTO_GENERATED')),
    CONSTRAINT uq_coords_name UNIQUE (name, latitude, longitude)
);

CREATE OR REPLACE FUNCTION calculate_distance_meters(
    lat1 double precision,
    lon1 double precision,
    lat2 double precision,
    lon2 double precision
) RETURNS double precision AS
$$
SELECT 6371000 * 2 * ATAN2(
        SQRT(
                SIN(RADIANS(lat2 - lat1) / 2) ^ 2 +
                COS(RADIANS(lat1)) * COS(RADIANS(lat2)) * SIN(RADIANS(lon2 - lon1) / 2) ^ 2
        ),
        SQRT(1 - (
            SIN(RADIANS(lat2 - lat1) / 2) ^ 2 +
            COS(RADIANS(lat1)) * COS(RADIANS(lat2)) * SIN(RADIANS(lon2 - lon1) / 2) ^ 2
            ))
                     )
$$ LANGUAGE SQL;
