package ru.practicum.ewm.location.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import ru.practicum.ewm.location.model.Location;
import ru.practicum.ewm.location.model.LocationState;

import java.util.Optional;

public interface LocationRepository extends
        JpaRepository<Location, Long>,
        JpaSpecificationExecutor<Location> {

    @Query(value = """
        SELECT * FROM locations l
        WHERE l.name = :name
            AND calculate_distance_meters(:lat, :lon, l.latitude, l.longitude) <= :radius
        LIMIT 1
        """, nativeQuery = true)
    Optional<Location> findDuplicates(
            @Param("name") String name,
            @Param("lat") double lat,
            @Param("lon") double lon,
            @Param("radius") double radius
    );

    @Query(value = """
        SELECT * FROM locations l
        WHERE l.state = 'AUTO_GENERATED'
            AND calculate_distance_meters(:latitude, :longitude, l.latitude, l.longitude) <= 20
        LIMIT 1
        """, nativeQuery = true)
    Optional<Location> findNearByAutoGenerated(Double latitude, Double longitude);

    Optional<Location> findByIdAndState(Long id, LocationState state);
}
